import { Container, Row, Col} from "react-bootstrap"

export default function Items() {
  return (
    <Container className="p-3 rounded-3 my-2">
        <Row className="gap-3">
            <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MONITOR</h1>
                <p> an output device that displays information from a computer, allowing users to interact visually with their computer. It's essentially a screen that shows text, images, videos, and other graphical information generated by the computer. Essentially, it's the visual display that allows you to see what your computer is doing. </p>
            </Col>
            <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">CPU</h1>
                <p>the "brain" of a computer, responsible for executing instructions and performing calculations. It's the core component that handles all the data processing and logic operations within a computer system. Essentially, it's the part of the computer that interprets and carries out commands from software, manages other hardware components, and allows users to interact with their devices. </p>
            </Col>
            <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">VIDEO CARD</h1>
                <p>a hardware component in a computer that processes and renders images, videos, and animations for display on a monitor. It essentially translates digital data into visual information that users can see.</p>
            </Col>
            <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MEMORY CARD</h1>
                <p>a small, portable storage device that uses flash memory to store digital data, such as photos, videos, and documents. It is commonly used in electronic devices like digital cameras, smartphones, and gaming consoles to expand storage capacity or transfer data. </p>
            </Col>
            <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">POWER SUPPLY</h1>
                <p>converts the alternating current (AC) from a wall outlet into the direct current (DC) needed to power the computer's internal components. It essentially acts as an electrical converter, taking the standard household electricity and transforming it into the specific voltages required by the motherboard, processor, and other parts of the computer. </p>
            </Col>
            <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MOTHERBOARD</h1>
                <p>the main circuit board in a computer system. It connects all of the internal components, like the memory, processor, graphics card and other hardware. It also provides power to each component and allows them to communicate with each other.</p>
            </Col>
                        <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MOTHERBOARD</h1>
                <p>the main circuit board in a computer system. It connects all of the internal components, like the memory, processor, graphics card and other hardware. It also provides power to each component and allows them to communicate with each other.</p>
            </Col>
                        <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MOTHERBOARD</h1>
                <p>the main circuit board in a computer system. It connects all of the internal components, like the memory, processor, graphics card and other hardware. It also provides power to each component and allows them to communicate with each other.</p>
            </Col>
                        <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MOTHERBOARD</h1>
                <p>the main circuit board in a computer system. It connects all of the internal components, like the memory, processor, graphics card and other hardware. It also provides power to each component and allows them to communicate with each other.</p>
            </Col>
                        <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MOTHERBOARD</h1>
                <p>the main circuit board in a computer system. It connects all of the internal components, like the memory, processor, graphics card and other hardware. It also provides power to each component and allows them to communicate with each other.</p>
            </Col>
                        <Col className="border border-dark text-center p-3 rounded-5 shadow">
                <h1 className="fw-bold">MOTHERBOARD</h1>
                <p>the main circuit board in a computer system. It connects all of the internal components, like the memory, processor, graphics card and other hardware. It also provides power to each component and allows them to communicate with each other.</p>
            </Col>
        </Row>
    </Container>
  )
}
